version: '3.8'

services:
  # PostgreSQL test database
  postgres-test:
    image: postgres:15-alpine
    container_name: coinlink-postgres-test
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=coinlink_test
      - POSTGRES_USER=coinlink_test
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coinlink_test -d coinlink_test"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Redis test instance
  redis-test:
    image: redis:7-alpine
    container_name: coinlink-redis-test
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    restart: "no"
    command: redis-server --appendonly no --maxmemory 128mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Backend API for testing
  backend-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: coinlink-backend-test
    ports:
      - "8001:8000"
    environment:
      # Test Database
      - DATABASE_URL=postgresql+asyncpg://coinlink_test:test_password@postgres-test:5432/coinlink_test
      # Test Redis
      - REDIS_URL=redis://redis-test:6379
      # Test Security
      - JWT_SECRET_KEY=test_jwt_secret_key_for_testing_only_not_production
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
      - PASSWORD_HASH_ROUNDS=4
      - SESSION_TIMEOUT_HOURS=1
      # Disable external APIs in tests
      - COINBASE_API_KEY=test_key
      - COINBASE_API_SECRET=test_secret
      - COINBASE_KEY_JSON={}
      - COINGECKO_API_KEY=test_key
      - HF_TOKEN=test_token
      - REDDIT_API_SECRET=test_secret
      - REDDIT_CLIENT_ID=test_client
      - NEWSAPI_API_KEY=test_key
      - MESSARI_API_KEY=test_key
      # Test Observability
      - SENTRY_DSN=
      - LOG_LEVEL=DEBUG
      - METRICS_ENABLED=false
      - PROMETHEUS_PORT=9091
      # Test Application
      - ENVIRONMENT=testing
      - API_V1_STR=/api/v1
      - MAX_CONNECTIONS_COUNT=5
      - MIN_CONNECTIONS_COUNT=1
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - test-network

volumes:
  postgres_test_data:
    driver: local
  redis_test_data:
    driver: local

networks:
  test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16