services:
  - type: web
    name: coinlink-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: CORS_ORIGINS  
        value: https://www.coin.link,https://coin.link,https://frontend-5larh80fr-shayans-projects-ede8d66b.vercel.app